version: '3'

services:
    redis:
        image: redis:latest
        container_name: redis_server
        command: bash -c 'redis-server'

    web:
        build: .
        command: bash -c 'python3 status_checker/manage.py makemigrations &&
                          python3 status_checker/manage.py migrate && 
                          python3 status_checker/manage.py runserver 0.0.0.0:8000'
        volumes: 
            - .:/code
        ports: 
            - "8000:8000"
        links:
          - redis
        depends_on:
          - redis
        restart: always

    celery:
        build: .
        volumes:
          - .:/code
        container_name: celery_worker
        command: bash -c 'cd status_checker/ && 
                          celery -A status_checker worker -B -l INFO'
        depends_on:
          - redis
        restart: always

    celery-beat:
        build: .
        volumes:
          - .:/code
        container_name: celery_broker
        command: bash -c 'cd status_checker/ && 
                          celery -A status_checker beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler'
        depends_on:
          - redis
        restart: always

      