# Generated by Django 3.1.3 on 2020-11-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=128)),
                ('interval_check', models.IntegerField(blank=True, null=True, verbose_name='in seconds')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('last_request', models.TimeField()),
            ],
        ),
    ]
